export type SiteSettingsMap = Record<string, unknown>;

export const DEFAULT_SETTINGS: SiteSettingsMap = {
  "general.siteName": "CodeBazaar",
  "general.tagline": "Digital marketplace for code & creatives",
  "general.supportEmail": "support@codebazaar.com",
  "general.currency": "USD",
  "general.logoUrl": "",
  "general.faviconUrl": "",
  "header.showBecomeSeller": false,
  "header.announcement": "",
  "header.announcementEnabled": false,
  "footer.aboutText": "The marketplace for high-quality code, scripts, plugins, and digital assets.",
  "footer.copyright": "© CodeBazaar. All prices in USD.",
  "footer.social": { twitter: "", github: "", linkedin: "" },
  "homepage.heroTitle": "Code that powers your next product",
  "homepage.heroHighlight": "your next product",
  "homepage.heroSubtitle": "Discover premium scripts, themes, plugins, and templates from world-class independent creators.",
  "homepage.heroCtaText": "Search",
  "homepage.heroCtaLink": "/search",
  "homepage.showCategories": true,
  "homepage.showFeatured": true,
  "homepage.showBestsellers": true,
  "homepage.showTrustBlocks": true,
  "homepage.statsSold": 128450,
  "homepage.statsEarnings": 4250000,
  "seo.defaultTitle": "CodeBazaar — Digital Marketplace for Code & Creatives",
  "seo.titleTemplate": "%s | CodeBazaar",
  "seo.defaultDescription": "Buy and sell high-quality scripts, plugins, themes, and digital assets.",
  "seo.ogImage": "",
  "seo.twitterHandle": "",
  "seo.robotsIndex": true,
  "seo.googleAnalyticsId": "",
  "seo.googleSearchConsole": "",
};
