import type { ItemCardData } from "@/types";

const PLACEHOLDER = (seed: number) =>
  `https://picsum.photos/seed/cb${seed}/640/400`;

export const MOCK_ITEMS: ItemCardData[] = [
  {
    id: "1",
    slug: "react-dashboard-pro",
    title: "React Admin Dashboard Pro — Modern Analytics UI Kit",
    thumbnailUrl: PLACEHOLDER(1),
    regularPrice: 49,
    extendedPrice: 249,
    salePriceRegular: 29,
    ratingAvg: 4.8,
    ratingCount: 312,
    salesCount: 4850,
    author: { username: "pixelcraft", avatarUrl: null },
    category: { name: "JavaScript", slug: "javascript" },
  },
  {
    id: "2",
    slug: "laravel-ecommerce-suite",
    title: "Laravel eCommerce Suite with Multi-Vendor Support",
    thumbnailUrl: PLACEHOLDER(2),
    regularPrice: 79,
    extendedPrice: 399,
    ratingAvg: 4.9,
    ratingCount: 187,
    salesCount: 2103,
    author: { username: "codeforge", avatarUrl: null },
    category: { name: "PHP Scripts", slug: "php-scripts" },
  },
  {
    id: "3",
    slug: "wordpress-saas-theme",
    title: "Nova — SaaS Landing & Blog WordPress Theme",
    thumbnailUrl: PLACEHOLDER(3),
    regularPrice: 59,
    extendedPrice: 299,
    salePriceRegular: 39,
    ratingAvg: 4.7,
    ratingCount: 524,
    salesCount: 8920,
    author: { username: "themewright", avatarUrl: null },
    category: { name: "WordPress", slug: "wordpress" },
  },
  {
    id: "4",
    slug: "flutter-finance-app",
    title: "FinTrack — Flutter Finance & Budget Mobile App",
    thumbnailUrl: PLACEHOLDER(4),
    regularPrice: 69,
    extendedPrice: 349,
    ratingAvg: 4.6,
    ratingCount: 98,
    salesCount: 1456,
    author: { username: "mobilelab", avatarUrl: null },
    category: { name: "Mobile", slug: "mobile" },
  },
  {
    id: "5",
    slug: "ai-chatbot-kit",
    title: "AetherBot — AI Chatbot Starter Kit for Next.js",
    thumbnailUrl: PLACEHOLDER(5),
    regularPrice: 89,
    extendedPrice: 449,
    ratingAvg: 4.9,
    ratingCount: 76,
    salesCount: 987,
    author: { username: "neuraldev", avatarUrl: null },
    category: { name: "AI Tools", slug: "ai-tools" },
  },
  {
    id: "6",
    slug: "html5-portfolio-kit",
    title: "Horizon — HTML5 Portfolio & Agency Template Pack",
    thumbnailUrl: PLACEHOLDER(6),
    regularPrice: 29,
    extendedPrice: 149,
    ratingAvg: 4.5,
    ratingCount: 210,
    salesCount: 3201,
    author: { username: "pixelcraft", avatarUrl: null },
    category: { name: "HTML5", slug: "html5" },
  },
  {
    id: "7",
    slug: "vue-kanban-board",
    title: "VueFlow — Kanban & Project Management Board",
    thumbnailUrl: PLACEHOLDER(7),
    regularPrice: 39,
    extendedPrice: 199,
    ratingAvg: 4.8,
    ratingCount: 143,
    salesCount: 1876,
    author: { username: "vueforge", avatarUrl: null },
    category: { name: "JavaScript", slug: "javascript" },
  },
  {
    id: "8",
    slug: "woocommerce-subscription",
    title: "SubscribePro — WooCommerce Subscriptions Extension",
    thumbnailUrl: PLACEHOLDER(8),
    regularPrice: 49,
    extendedPrice: 249,
    ratingAvg: 4.7,
    ratingCount: 289,
    salesCount: 4120,
    author: { username: "themewright", avatarUrl: null },
    category: { name: "WordPress", slug: "wordpress" },
  },
];

export const CATEGORY_CARDS = [
  { name: "WordPress", slug: "wordpress", description: "Themes, plugins & WooCommerce", icon: "🟦" },
  { name: "PHP Scripts", slug: "php-scripts", description: "Laravel, CodeIgniter & scripts", icon: "🐘" },
  { name: "Mobile", slug: "mobile", description: "React Native, Flutter & apps", icon: "📱" },
  { name: "HTML5", slug: "html5", description: "Landing pages & admin templates", icon: "🌐" },
  { name: "JavaScript", slug: "javascript", description: "React, Vue, Node & kits", icon: "⚡" },
  { name: "Plugins", slug: "plugins", description: "Browser, IDE & design plugins", icon: "🔌" },
];
